services:
  - type: web
    name: akhyana-peerjs
    env: node
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && node peerjs-server.js
    envVars:
      - key: PORT
        value: 9000
    plan: free
    
  - type: web
    name: akhyana-websocket
    env: node
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && node server.js
    envVars:
      - key: PORT
        value: 3002
    plan: free
